base:
  random_state: 36
  target_col: class
  test_size: 0.33

app:
  host: 0.0.0.0
  port: 8080

data:
  raw_data:
    train_batch: training_data
    pred_batch: prediction_data

  train:
    good_data_dir: good/train
    bad_data_dir: bad/train

  pred:
    good_data_dir: good/pred
    bad_data_dir: bad/pred

mongodb:
  air_pressure_data_db_name: air_pressure-data
  air_pressure_train_data_collection: air_pressure-train-data
  air_pressure_pred_data_collection: air_pressure-pred-data

knn_imputer:
  n_neighbors: 3
  weights: uniform

kmeans_cluster:
  init: k-means++
  max_clusters: 11
  knee:
    curve: convex
    direction: decreasing

pca_model:
  n_components: 100

s3_bucket:
  input_files_bucket: air_pressure-io-files
  air_pressure_model_bucket: air_pressure-model
  air_pressure-mlflow_bucket: air_pressure-mlflow
  air_pressure_pred_data_bucket: air_pressure-pred-data
  air_pressure_train_data_bucket: air_pressure-train-data
  air_pressure_raw_data_bucket: air_pressure-raw-data
  air_pressure_logs_bucket: air-pressure-logs

models_dir:
  trained: trained
  stag: staging
  prod: production

model_utils:
  verbose: 3
  cv: 5
  n_jobs: -1
  save_format: .sav

model_params:
  rf_model:
    n_estimators:
      - 10
      - 50
      - 100
      - 130

    criterion:
      - gini
      - entropy

    max_features:
      - auto
      - log2

    max_depth:
      - 2
      - 3
      - 4
      - 5

  adaboost_model:
    n_estimators:
      - 10
      - 50
      - 100
      - 130

    learning_rate:
      - 0.5
      - 0.1
      - 0.01
      - 0.001

    random_state:
      - 0
      - 100
      - 200
      - 300

mlflow_config:
  experiment_name: air_pressure-exp-1
  run_name: mlops
  serialization_format: cloudpickle

db_log.txt:
  train: air_pressure_training_log.txt
  pred: air_pressure_prediction_log.txt

train_db_log:
  model_training: model_training_log.txt
  col_validation: train_col_validation_log.txt
  data_transform: train_data_transform_log.txt
  export_csv: train_export_csv_log.txt
  general: train_general_log.txt
  db_insert: train_db_insert_log.txt
  load_prod_model: load_prod_model_log.txt
  missing_values_in_col: train_missing_values_log.txt
  name_validation: train_name_validation_log.txt
  train_main: train_main_log.txt
  values_from_schema: train_values_from_schema_log.txt

pred_db_log.txt:
  col_validation: pred_col_validation_log.txt
  data_transform: pred_data_transform_log.txt
  db_insert: pred_db_insert_log.txt
  export_csv: pred_export_csv_log.txt
  general: pred_general_log.txt
  missing_values_in_col: pred_missing_values_log.txt
  name_validation: pred_name_validation_log.txt
  pred_main: pred_main_log.txt
  values_from_schema: pred_values_from_schema_log.txt

schema_file:
  train_schema_file: air_pressure_schema_training.json
  pred_schema_file: air_pressure_schema_prediction.json

elbow_plot_fig: K-Means_Elbow.PNG

null_values_csv_file: null_values.csv

pred_output_file: predictions.csv

regex_file: air_pressure_regex.txt

export_csv_file:
  train: train_input_file.csv
  pred: pred_input_file.csv

templates:
  dir: templates
  index_html_file: index.html
